### PR TITLE
Fix a typo in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by izzergh**
you -> your

also changes the list indices to be 1, and allow Mark Down to take the wheel

Also, I couldn't do (4) because I don't have CI set up on my fork - are forkers expected to set up CI, or should I move that step to after the "create a PR" step?

### CODE REVIEW

**Comment by izzergh** [comment]
D: I also can't request a reviewer!

**Comment by cam-ball** [comment]
I'm super surprised you can't request a reviewer @izzergh! do you think you could edit that step in the guide to say something along the lines of "request a reviewer or tag @laurenball" ?

travis looks like it [*did* run](https://travis-ci.org/github/laurenball/Steven/jobs/758615981) but failed. that is obviously not related to your changes here and seems to be a .env problem. I'll take a look and see if there's some setting I'm missing there.

Thanks for fixing my typo, and also I had no idea that that's how markdown lists work, very neat, TIL, etc :revolving_hearts:

**Comment by cam-ball** [comment]
on further investigation, it doesn't look there's a great way for me to make the travis build work for a fork due to the way that environment variables are set. If you're not opposed to doing that as well, I'd also appreciate removing that line @izzergh 

so, in summary
1) add something about pinging me to the request step
2) remove the CI step entirely

and if you don't want to do that, I'll open an issue or take care of it myself.

**Comment by izzergh** [comment]
I will do what you summarized @laurenball

**Comment by izzergh** [comment]
@laurenball could you review this? (per the candidate updated contribution guidelines)

**Review by cam-ball — APPROVED** [review]
:chef_kiss:

**Pull request merged**
